/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Ship(props) {
  const { nodes, materials } = useGLTF('/pirateship.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.1}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mast_middle_pirateship_0.geometry}
          material={materials.pirateship}
          position={[0, 10, -10]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mast_bottom_pirateship_0.geometry}
          material={materials.pirateship}
          position={[0, 10, -10]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.hull_frontSmooth_pirateship_0.geometry}
          material={materials.pirateship}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.post_wall_pirateship_0.geometry}
          material={materials.pirateship}
          position={[13, 21, -10.25]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1, 1, 3]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.post_wall_pirateship_0_1.geometry}
          material={materials.pirateship}
          position={[-13, 21, -10.25]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[1, 1, 3]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.hull_back_pirateship_0.geometry}
          material={materials.pirateship}
          position={[0, 0, -30]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mast_middle_pirateship_0_1.geometry}
          material={materials.pirateship}
          position={[0, 20, -20]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mast_middle_pirateship_0_2.geometry}
          material={materials.pirateship}
          position={[0, 29, -20]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mast_bottomDetailed_pirateship_0.geometry}
          material={materials.pirateship}
          position={[0, 12, -36]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mast_middle_pirateship_0_3.geometry}
          material={materials.pirateship}
          position={[0, 9.5, 3.134]}
          rotation={[Math.PI / 3, 0, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_tireEmergencyAttachment_pirateship_0.geometry}
          material={materials.pirateship}
          position={[-5, 7, -10]}
          rotation={[Math.PI / 2, 0, Math.PI / 2]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sail_triangle_pirateship_0.geometry}
          material={materials.pirateship}
          position={[0, 18.776, 5.898]}
          rotation={[-0.262, 0, 0]}
          scale={[1.21, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tube_steelAlternate_pirateship_0.geometry}
          material={materials.pirateship}
          position={[-0.269, 31.668, -9.553]}
          rotation={[2.094, 0, 0]}
          scale={[0.269, 1.23, 0.271]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mast_middle_pirateship_0_4.geometry}
          material={materials.pirateship}
          position={[0, 20, -10]}
          scale={[1, 1.21, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tube_steelAlternate_pirateship_0_1.geometry}
          material={materials.pirateship}
          position={[-0.336, 7.695, -4.407]}
          rotation={[Math.PI / 6, 0, 0]}
          scale={[0.336, 1.403, 0.292]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tube_steelAlternate_pirateship_0_2.geometry}
          material={materials.pirateship}
          position={[-0.336, 7.695, -4.407]}
          rotation={[Math.PI / 6, 0, 0]}
          scale={[0.336, 1.403, 0.292]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tube_steelAlternate_pirateship_0_3.geometry}
          material={materials.pirateship}
          position={[-5.106, 9.949, -12.791]}
          rotation={[0.262, 0, Math.PI / 6]}
          scale={[0.313, 1.293, 0.28]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tube_steelAlternate_pirateship_0_4.geometry}
          material={materials.pirateship}
          position={[5.064, 10.258, -12.473]}
          rotation={[0.262, 0, -Math.PI / 4]}
          scale={[0.351, 1.447, 0.294]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.rail_frontSmoothDeck_pirateship_0.geometry}
          material={materials.pirateship}
          position={[0, 10, 0]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mast_bottom_pirateship_0_1.geometry}
          material={materials.pirateship}
          position={[0, 16, -36]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mast_middle_pirateship_0_5.geometry}
          material={materials.pirateship}
          position={[0, 24, -36]}
          scale={[1, 1.2, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.post_wall_pirateship_0_2.geometry}
          material={materials.pirateship}
          position={[-13, 26, -36.25]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[1, 1, 3]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.post_wall_pirateship_0_3.geometry}
          material={materials.pirateship}
          position={[13, 26, -36.25]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1, 1, 3]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sail_pirateship_0.geometry}
          material={materials.pirateship}
          position={[1.83, 23, -35.625]}
          scale={[2.754, 1.2, 1.3]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.hut_openHalf_pirateship_0.geometry}
          material={materials.pirateship}
          position={[-4.844, 20, -33.732]}
          scale={[0.441, 0.6, 0.68]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tank_turretBarrelLarge_pirateship_0.geometry}
          material={materials.pirateship}
          position={[5.158, 11.669, -19.711]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.405, 0.621, 0.353]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheel_classic_pirateship_0.geometry}
          material={materials.pirateship}
          position={[3.495, 10.904, -12.901]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.405, 0.316, 0.115]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_engine_pirateship_0.geometry}
          material={materials.pirateship}
          position={[3.159, 10.691, -13.711]}
          rotation={[Math.PI / 2, -Math.PI / 3, Math.PI / 2]}
          scale={[0.405, 0.783, 0.509]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tank_turretBarrelLarge_pirateship_0_1.geometry}
          material={materials.pirateship}
          position={[5.158, 11.669, -13.711]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.405, 0.621, 0.353]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheel_classic_pirateship_0_1.geometry}
          material={materials.pirateship}
          position={[3.495, 10.904, -15.331]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.405, 0.316, 0.115]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheel_classic_pirateship_0_2.geometry}
          material={materials.pirateship}
          position={[-3.188, 10.904, -14.455]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.405, 0.316, 0.115]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_engine_pirateship_0_1.geometry}
          material={materials.pirateship}
          position={[-2.852, 10.691, -13.645]}
          rotation={[Math.PI / 2, Math.PI / 3, -Math.PI / 2]}
          scale={[0.405, 0.783, 0.509]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tank_turretBarrelLarge_pirateship_0_2.geometry}
          material={materials.pirateship}
          position={[-4.851, 11.669, -13.645]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.405, 0.621, 0.353]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheel_classic_pirateship_0_3.geometry}
          material={materials.pirateship}
          position={[-3.188, 10.904, -12.025]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.405, 0.316, 0.115]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheel_classic_pirateship_0_4.geometry}
          material={materials.pirateship}
          position={[-3.188, 10.904, -21.455]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.405, 0.316, 0.115]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheel_classic_pirateship_0_5.geometry}
          material={materials.pirateship}
          position={[-3.188, 10.904, -19.025]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.405, 0.316, 0.115]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.fence_classicFarm_pirateship_0.geometry}
          material={materials.pirateship}
          position={[-0.082, 30, -22.5]}
          scale={[1.016, 0.7, 0.9]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.fence_classicFarm_pirateship_0_1.geometry}
          material={materials.pirateship}
          position={[-0.137, 30, -21.5]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1.016, 0.7, 1.089]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.fence_classicFarm_pirateship_0_2.geometry}
          material={materials.pirateship}
          position={[-0.137, 30, -21.5]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[1.016, 0.7, 1.089]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sail_pirateship_0_1.geometry}
          material={materials.pirateship}
          position={[1.83, 18, -8.625]}
          scale={[2.754, 1.2, 1.3]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.fence_classicFarm_pirateship_0_3.geometry}
          material={materials.pirateship}
          position={[-0.137, 30, -21.5]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[1.016, 0.7, 1.089]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.post_wall_pirateship_0_4.geometry}
          material={materials.pirateship}
          position={[13, 21, -20.25]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[1, 1, 3]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mast_middle_pirateship_0_6.geometry}
          material={materials.pirateship}
          position={[-6.368, 39.149, -19.775]}
          rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          scale={[1.14, 1.365, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.platform_woodHole_pirateship_0.geometry}
          material={materials.pirateship}
          position={[-0.5, 30, -21.05]}
          scale={[1.1, 1, 1.21]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tube_steelAlternate_pirateship_0_5.geometry}
          material={materials.pirateship}
          position={[-4.453, 9.6, -22.189]}
          rotation={[0.262, 0, Math.PI / 6]}
          scale={[0.321, 1.323, 0.283]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tube_steelAlternate_pirateship_0_6.geometry}
          material={materials.pirateship}
          position={[5.064, 9.856, -21.898]}
          rotation={[0.262, 0, -Math.PI / 4]}
          scale={[0.351, 1.447, 0.294]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.hull_pirateship_0.geometry}
          material={materials.pirateship}
          position={[0, 0, -20]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.rail_pirateship_0.geometry}
          material={materials.pirateship}
          position={[0, 10, -30]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.hull_pirateship_0_1.geometry}
          material={materials.pirateship}
          position={[0, 0, -10]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_engine_pirateship_0_2.geometry}
          material={materials.pirateship}
          position={[3.159, 10.691, -19.711]}
          rotation={[Math.PI / 2, -Math.PI / 3, Math.PI / 2]}
          scale={[0.405, 0.783, 0.509]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheel_classic_pirateship_0_6.geometry}
          material={materials.pirateship}
          position={[3.495, 10.904, -18.901]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.405, 0.316, 0.115]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.wheel_classic_pirateship_0_7.geometry}
          material={materials.pirateship}
          position={[3.495, 10.904, -21.331]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.405, 0.316, 0.115]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.gate_pirateship_0.geometry}
          material={materials.pirateship}
          position={[1.5, 17.745, -25]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[2.849, 0.3, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mast_bottom_pirateship_0_2.geometry}
          material={materials.pirateship}
          position={[0, 10, -20]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mast_bottomDetailed_pirateship_0_1.geometry}
          material={materials.pirateship}
          position={[0, 10, -20]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.detail_engine_pirateship_0_3.geometry}
          material={materials.pirateship}
          position={[-2.852, 10.691, -20.645]}
          rotation={[Math.PI / 2, Math.PI / 3, -Math.PI / 2]}
          scale={[0.405, 0.783, 0.509]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.hut_hexagon_pirateship_0.geometry}
          material={materials.pirateship}
          position={[-4.88, 15, -33.5]}
          scale={[0.48, 0.6, 0.7]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tank_turretBarrelLarge_pirateship_0_3.geometry}
          material={materials.pirateship}
          position={[-4.851, 11.669, -20.645]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.405, 0.621, 0.353]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tube_steelAlternate_pirateship_0_7.geometry}
          material={materials.pirateship}
          position={[5.882, 15.574, -39.372]}
          rotation={[0.262, 0, -Math.PI / 4]}
          scale={[0.323, 1.314, 0.283]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.hull_backEdge_pirateship_0.geometry}
          material={materials.pirateship}
          position={[0.75, 5, -38]}
          scale={[1.65, 1.08, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.stairs_woodRailing_pirateship_0.geometry}
          material={materials.pirateship}
          position={[2.563, 10, -29.146]}
          scale={[0.5, 0.64, 0.6]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.window_round_pirateship_0.geometry}
          material={materials.pirateship}
          position={[10, 3, -23.145]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.6, 0.7, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.window_round_pirateship_0_1.geometry}
          material={materials.pirateship}
          position={[10, 3, -16.145]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.6, 0.7, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.window_round_pirateship_0_2.geometry}
          material={materials.pirateship}
          position={[10, 3, -9.145]}
          rotation={[0, Math.PI / 2, 0]}
          scale={[0.6, 0.7, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.window_round_pirateship_0_3.geometry}
          material={materials.pirateship}
          position={[-10, 3, -9.145]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.6, 0.7, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.window_round_pirateship_0_4.geometry}
          material={materials.pirateship}
          position={[-10, 3, -25.145]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[0.6, 0.7, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.door_rounded_wide_pirateship_0.geometry}
          material={materials.pirateship}
          position={[-1.087, 10, -28]}
          scale={[0.7, 0.5, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.window_detail_pirateship_0.geometry}
          material={materials.pirateship}
          position={[14.994, 9.98, -50.965]}
          rotation={[2.88, 0, Math.PI / 2]}
          scale={[1.281, 2.808, 1.887]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mast_bottomDetailed_pirateship_0_2.geometry}
          material={materials.pirateship}
          position={[0, 10, -10]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.banner_red_pirateship_0.geometry}
          material={materials.pirateship}
          position={[-0.3, 26.7, -15]}
          scale={[1.68, 1.43, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tube_steelAlternate_pirateship_0_8.geometry}
          material={materials.pirateship}
          position={[-4.658, 14.955, -39.542]}
          rotation={[0.262, 0, Math.PI / 6]}
          scale={[0.302, 1.227, 0.275]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.rail_back_pirateship_0.geometry}
          material={materials.pirateship}
          position={[0.42, 15, -38]}
          scale={[1.716, 1, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.sail_pirateship_0_2.geometry}
          material={materials.pirateship}
          position={[1.83, 18, -18.625]}
          scale={[2.754, 1.2, 1.3]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.block_pirateship_0.geometry}
          material={materials.pirateship}
          position={[-4.5, 0, -18]}
          scale={[3.9, 0.1, 7.4]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.rail_pirateship_0_1.geometry}
          material={materials.pirateship}
          position={[0, 10, -17]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.post_wall_pirateship_0_5.geometry}
          material={materials.pirateship}
          position={[-13, 21, -20.25]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={[1, 1, 3]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mast_middle_pirateship_0_7.geometry}
          material={materials.pirateship}
          position={[0, 13.687, 10.083]}
          rotation={[Math.PI / 3, 0, 0]}
          scale={[1, 1.038, 1.011]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.tube_steelAlternate_pirateship_0_9.geometry}
          material={materials.pirateship}
          position={[-0.269, 20.389, 10.268]}
          rotation={[2.094, 0, 0]}
          scale={[0.269, 0.784, 0.19]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.mast_bottomDetailed_pirateship_0_3.geometry}
          material={materials.pirateship}
          position={[0, 9.565, 3.301]}
          rotation={[Math.PI / 3, 0, 0]}
          scale={[1, 1.346, 1.264]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/pirateship.glb')
