/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export function Ship(props) {
  const { nodes, materials } = useGLTF('/trial.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={nodes.Plane.material}
        position={[-0.147, -0.147, 0.147]}
        rotation={[-0.087, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.BézierCurve006.geometry}
          material={nodes.BézierCurve006.material}
          position={[0.039, 0, 1.019]}
          scale={0.574}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={nodes.Cube.material}
          position={[0, 1.633, -4.899]}
          scale={[1.897, 0.691, 1]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={nodes.Cube001.material}
          position={[1.051, 1.652, 1.066]}
          rotation={[-0.157, 0.954, 0]}
          scale={[1.8, 0.102, 0.102]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube002.geometry}
          material={nodes.Cube002.material}
          position={[2.06, 1.404, -1.702]}
          rotation={[-1.517, 1.48, 1.504]}
          scale={[1.398, 0.102, 0.102]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003.geometry}
          material={nodes.Cube003.material}
          position={[2.06, 1.765, -3.704]}
          rotation={[-1.517, 1.48, 1.504]}
          scale={[0.446, 0.102, 0.102]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004.geometry}
          material={nodes.Cube004.material}
          position={[1.942, 3.805, -5.602]}
          rotation={[-1.517, 1.48, 1.504]}
          scale={[1.115, 0.102, 0.102]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005.geometry}
          material={nodes.Cube005.material}
          position={[2.047, 1.61, -3.173]}
          rotation={[-0.709, 1.48, 1.504]}
          scale={[0.255, 0.102, 0.102]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006.geometry}
          material={nodes.Cube006.material}
          position={[2.045, 2.771, -4.399]}
          rotation={[-0.201, 1.48, 1.504]}
          scale={[1.101, 0.102, 0.102]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube007.geometry}
          material={nodes.Cube007.material}
          position={[-1.94, 1.404, -1.702]}
          rotation={[-1.517, 1.48, 1.504]}
          scale={[1.398, 0.102, 0.102]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube008.geometry}
          material={nodes.Cube008.material}
          position={[-1.94, 1.765, -3.704]}
          rotation={[-1.517, 1.48, 1.504]}
          scale={[0.446, 0.102, 0.102]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube009.geometry}
          material={nodes.Cube009.material}
          position={[-2.003, 3.798, -5.609]}
          rotation={[1.53, 1.452, -1.543]}
          scale={[1.115, 0.102, 0.102]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube010.geometry}
          material={nodes.Cube010.material}
          position={[-1.953, 1.61, -3.173]}
          rotation={[-0.709, 1.48, 1.504]}
          scale={[0.255, 0.102, 0.102]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube011.geometry}
          material={nodes.Cube011.material}
          position={[0.004, 2.715, -5.329]}
          scale={[1.901, 0.55, 0.795]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube015.geometry}
            material={nodes.Cube015.material}
            position={[-0.994, -0.768, 1.488]}
            rotation={[-1.492, -1.4, -1.368]}
            scale={[0.346, 0.145, 0.044]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube016.geometry}
            material={nodes.Cube016.material}
            position={[1.005, -0.768, 1.488]}
            rotation={[1.461, -1.321, 1.239]}
            scale={[0.346, 0.144, 0.047]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube022.geometry}
            material={nodes.Cube022.material}
            position={[0.98, 0.891, 0.719]}
            rotation={[1.461, -1.321, 1.239]}
            scale={[0.346, 0.144, 0.047]}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube023.geometry}
            material={nodes.Cube023.material}
            position={[-0.976, 1.019, 0.804]}
            rotation={[-1.492, -1.4, -1.368]}
            scale={[0.346, 0.145, 0.044]}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube012.geometry}
          material={nodes.Cube012.material}
          position={[-0.975, 1.654, 1.083]}
          rotation={[3.061, 0.976, 3.08]}
          scale={[1.8, 0.102, 0.102]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube013.geometry}
          material={nodes.Cube013.material}
          position={[0.03, 3.806, -6.61]}
          rotation={[-0.091, 0.001, -0.013]}
          scale={[1.98, 0.102, 0.102]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube014.geometry}
          material={nodes.Cube014.material}
          position={[0.01, 2.278, -3.918]}
          rotation={[-0.091, 0.001, -0.013]}
          scale={[1.963, 0.08, 0.08]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube017.geometry}
          material={nodes.Cube017.material}
          position={[0.003, 1.415, 2.075]}
          rotation={[-2.838, 1.561, 2.011]}
          scale={[0.688, 0.102, 0.14]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Cube018.geometry}
            material={nodes.Cube018.material}
            position={[1.723, -0.288, 0.027]}
            rotation={[0, 0.001, -0.234]}
            scale={[0.959, 0.997, 1]}
          />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube019.geometry}
          material={nodes.Cube019.material}
          position={[0.005, 2.443, 3.238]}
          rotation={[-2.647, 1.561, 2.011]}
          scale={[1.397, 0.208, 0.193]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube020.geometry}
          material={nodes.Cube020.material}
          position={[-1.926, 2.661, -4.329]}
          rotation={[-0.201, 1.48, 1.504]}
          scale={[1.101, 0.102, 0.102]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube021.geometry}
          material={nodes.Cube021.material}
          position={[0.01, 3.23, -4.508]}
          rotation={[-0.091, 0.001, -0.013]}
          scale={[1.963, 0.08, 0.08]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube024.geometry}
          material={nodes.Cube024.material}
          position={[-0.01, 4.809, -1.92]}
          rotation={[2.667, 1.561, 2.011]}
          scale={[3.389, 0.208, 0.487]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Torus001.geometry}
            material={nodes.Torus001.material}
            position={[0.823, 2.038, 0.023]}
            rotation={[-1.392, 1.3, -1.988]}
            scale={[0.331, 1.279, 0.055]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube044.geometry}
              material={nodes.Cube044.material}
              position={[0.002, -0.03, -0.023]}
              rotation={[-Math.PI, 0, 0]}
              scale={[-0.315, -0.218, -1]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube045.geometry}
              material={nodes.Cube045.material}
              position={[0.002, -0.03, -0.023]}
              rotation={[-Math.PI, -0.708, 0]}
              scale={[-0.315, -0.218, -1]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube046.geometry}
              material={nodes.Cube046.material}
              position={[0.002, -0.03, -0.023]}
              rotation={[-Math.PI, -1.404, 0]}
              scale={[-0.315, -0.218, -1]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube047.geometry}
              material={nodes.Cube047.material}
              position={[0.002, -0.03, -0.023]}
              rotation={[0, -1.038, Math.PI]}
              scale={[-0.315, -0.218, -1]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube048.geometry}
              material={nodes.Cube048.material}
              position={[0.002, -0.03, -0.023]}
              rotation={[0, -0.338, Math.PI]}
              scale={[-0.315, -0.218, -1]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube049.geometry}
              material={nodes.Cube049.material}
              position={[0.002, -0.03, -0.023]}
              rotation={[0, 0.358, Math.PI]}
              scale={[-0.315, -0.218, -1]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube050.geometry}
              material={nodes.Cube050.material}
              position={[0.002, -0.03, -0.023]}
              rotation={[0, 1.041, Math.PI]}
              scale={[-0.315, -0.218, -1]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube051.geometry}
              material={nodes.Cube051.material}
              position={[0.002, -0.03, -0.023]}
              rotation={[Math.PI, 1.413, 0]}
              scale={[-0.315, -0.218, -1]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cube052.geometry}
              material={nodes.Cube052.material}
              position={[0.002, -0.03, -0.023]}
              rotation={[-Math.PI, 0.702, 0]}
              scale={[-0.315, -0.218, -1]}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Cylinder014.geometry}
              material={nodes.Cylinder014.material}
              position={[-0.068, 0.054, -0.016]}
              scale={[1, 0.355, 1]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube054.geometry}
                material={nodes.Cube054.material}
                position={[0.045, -0.19, 0.045]}
                scale={[0.35, 0.599, 2.208]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube056.geometry}
                material={nodes.Cube056.material}
                position={[0.045, -0.19, 0.045]}
                rotation={[-Math.PI, 1.103, -Math.PI]}
                scale={[0.35, 0.599, 2.208]}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube057.geometry}
                material={nodes.Cube057.material}
                position={[0.045, -0.19, 0.045]}
                rotation={[Math.PI, -1.091, Math.PI]}
                scale={[0.35, 0.599, 2.208]}
              />
            </mesh>
          </mesh>
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube025.geometry}
          material={nodes.Cube025.material}
          position={[-0.019, 4.604, 0.701]}
          rotation={[2.667, 1.561, 2.011]}
          scale={[2.478, 0.152, 0.356]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube026.geometry}
          material={nodes.Cube026.material}
          position={[-0.009, 5.695, -5.376]}
          rotation={[2.667, 1.561, 2.011]}
          scale={[2.108, 0.129, 0.303]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube034.geometry}
          material={nodes.Cube034.material}
          position={[2.078, 1.362, -4.727]}
          rotation={[-1.517, 1.48, 1.504]}
          scale={[1.658, 0.102, 0.102]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube035.geometry}
          material={nodes.Cube035.material}
          position={[2.083, 2.051, -5.38]}
          rotation={[-1.517, 1.48, 1.504]}
          scale={[1.211, 0.102, 0.102]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube036.geometry}
          material={nodes.Cube036.material}
          position={[-2.022, 1.362, -4.727]}
          rotation={[-1.517, 1.48, 1.504]}
          scale={[1.658, 0.102, 0.102]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube037.geometry}
          material={nodes.Cube037.material}
          position={[-2.017, 2.051, -5.38]}
          rotation={[-1.517, 1.48, 1.504]}
          scale={[1.211, 0.102, 0.102]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube038.geometry}
          material={nodes.Cube038.material}
          position={[0.031, 2.061, -6.542]}
          rotation={[-0.091, 0, -0.003]}
          scale={[2.051, 0.102, 0.102]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube039.geometry}
          material={nodes.Cube039.material}
          position={[0.031, 1.343, -6.316]}
          rotation={[-0.091, 0, -0.003]}
          scale={[2.051, 0.102, 0.102]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube040.geometry}
          material={nodes.Cube040.material}
          position={[0.031, 3.161, -6.542]}
          rotation={[-0.091, 0, -0.003]}
          scale={[2.051, 0.102, 0.102]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube041.geometry}
          material={nodes.Cube041.material}
          position={[2.011, 3.145, -5.529]}
          rotation={[-1.517, 1.48, 1.504]}
          scale={[1.018, 0.102, 0.102]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube042.geometry}
          material={nodes.Cube042.material}
          position={[-2.04, 3.171, -5.459]}
          rotation={[-1.517, 1.48, 1.504]}
          scale={[1.018, 0.102, 0.102]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus002.geometry}
          material={nodes.Torus002.material}
          position={[0.364, 1.782, 2.418]}
          rotation={[1.213, -0.318, -1.262]}
          scale={0.163}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus004.geometry}
          material={nodes.Torus004.material}
          position={[2.225, 0.983, -3.183]}
          rotation={[-0.016, -0.011, -1.698]}
          scale={0.205}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus005.geometry}
          material={nodes.Torus005.material}
          position={[2.225, 0.983, -1.483]}
          rotation={[-0.016, -0.011, -1.698]}
          scale={0.205}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus006.geometry}
          material={nodes.Torus006.material}
          position={[2.225, 0.983, -4.883]}
          rotation={[-0.016, -0.011, -1.698]}
          scale={0.205}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus008.geometry}
          material={nodes.Torus008.material}
          position={[-2.138, 1.026, -3.183]}
          rotation={[-0.013, -0.015, -1.45]}
          scale={0.205}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus009.geometry}
          material={nodes.Torus009.material}
          position={[-2.138, 1.026, -1.483]}
          rotation={[-0.013, -0.015, -1.45]}
          scale={0.205}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Torus010.geometry}
          material={nodes.Torus010.material}
          position={[-2.138, 1.026, -4.883]}
          rotation={[-0.013, -0.015, -1.45]}
          scale={0.205}
        />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube043.geometry}
        material={nodes.Cube043.material}
        position={[3.539, 1.164, -5.264]}
        scale={[1.082, 0.068, 3.828]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={nodes.Cylinder.material}
        position={[4.263, 0.367, -1.757]}
        scale={[0.224, 0.764, 0.224]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={nodes.Cylinder001.material}
        position={[4.263, 0.367, -2.94]}
        scale={[0.224, 0.764, 0.224]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={nodes.Cylinder002.material}
        position={[4.263, 0.367, -4.07]}
        scale={[0.224, 0.764, 0.224]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder003.geometry}
        material={nodes.Cylinder003.material}
        position={[4.263, 0.367, -5.215]}
        scale={[0.224, 0.764, 0.224]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder004.geometry}
        material={nodes.Cylinder004.material}
        position={[4.263, 0.367, -6.265]}
        scale={[0.224, 0.764, 0.224]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder005.geometry}
        material={nodes.Cylinder005.material}
        position={[4.263, 0.367, -7.466]}
        scale={[0.224, 0.764, 0.224]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder006.geometry}
        material={nodes.Cylinder006.material}
        position={[4.263, 0.367, -8.712]}
        scale={[0.224, 0.764, 0.224]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder007.geometry}
        material={nodes.Cylinder007.material}
        position={[2.856, 0.367, -1.757]}
        scale={[0.224, 0.764, 0.224]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder008.geometry}
        material={nodes.Cylinder008.material}
        position={[2.856, 0.367, -2.94]}
        scale={[0.224, 0.764, 0.224]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder009.geometry}
        material={nodes.Cylinder009.material}
        position={[2.856, 0.367, -4.07]}
        scale={[0.224, 0.764, 0.224]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder010.geometry}
        material={nodes.Cylinder010.material}
        position={[2.856, 0.367, -5.215]}
        scale={[0.224, 0.764, 0.224]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder011.geometry}
        material={nodes.Cylinder011.material}
        position={[2.856, 0.367, -6.265]}
        scale={[0.224, 0.764, 0.224]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder012.geometry}
        material={nodes.Cylinder012.material}
        position={[2.856, 0.367, -7.466]}
        scale={[0.224, 0.764, 0.224]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder013.geometry}
        material={nodes.Cylinder013.material}
        position={[2.856, 0.367, -8.712]}
        scale={[0.224, 0.764, 0.224]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torus007.geometry}
        material={nodes.Torus007.material}
        position={[3.163, 1.005, -1.315]}
        rotation={[1.568, 0, 0]}
        scale={0.123}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torus003.geometry}
        material={nodes.Torus003.material}
        position={[4.053, 1.005, -1.315]}
        rotation={[1.568, 0, 0]}
        scale={0.123}
      />
      <PerspectiveCamera
        makeDefault={false}
        far={1000}
        near={0.1}
        fov={22.895}
        position={[20.131, 12.643, 15.217]}
        rotation={[-0.528, 0.803, 0.397]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={nodes.Plane001.material}
        scale={10.658}
      />
    </group>
  )
}

useGLTF.preload('/trial.glb')
